//
// File generated by HDevelop for HALCON/.NET (C#) Version 23.05.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Camera101, ho_Region;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Camera101);
    HOperatorSet.GenEmptyObj(out ho_Region);
    ho_Camera101.Dispose();
    HOperatorSet.ReadImage(out ho_Camera101, "C:/Users/Administrator/AppData/Roaming/MVTec/HALCON-23.05-Progress/examples/images/3d_machine_vision/multiple_cameras/camera1_01.png");
    ho_Region.Dispose();
    HOperatorSet.Threshold(ho_Camera101, out ho_Region, 1, 80);


    ho_Camera101.Dispose();
    ho_Region.Dispose();


  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

