//
// File generated by HDevelop for HALCON/.NET (C#) Version 23.05.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Heisi, ho_grayimg, ho_Regions;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Heisi);
    HOperatorSet.GenEmptyObj(out ho_grayimg);
    HOperatorSet.GenEmptyObj(out ho_Regions);
    ho_Heisi.Dispose();
    HOperatorSet.ReadImage(out ho_Heisi, "D:/Desktop/文档记录/heisi.png");
    //彩图转换为灰度图
    ho_grayimg.Dispose();
    HOperatorSet.Rgb1ToGray(ho_Heisi, out ho_grayimg);
    //阈值/灰度提取
    ho_Regions.Dispose();
    HOperatorSet.Threshold(ho_grayimg, out ho_Regions, 4, 110);


    ho_Heisi.Dispose();
    ho_grayimg.Dispose();
    ho_Regions.Dispose();


  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
//public class HDevelopExportApp
//{
//  static void Main(string[] args)
//  {
//    new HDevelopExport();
//  }
//}
#endif

